version: '3'
services:

  proxy:
    container_name: proxy
    image: nginx:latest
    volumes:  
      - ./nginx/logs:/logs:rw
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs/letsencrypt:/etc/nginx/certs/letsencrypt:ro
      - ./nginx/certs/crystal:/etc/nginx/certs/crystal:ro
      - ./nginx/certs/local:/etc/nginx/certs/local:ro
      - ./nginx/certs/sdk:/etc/nginx/certs/sdk:ro
    ports:
      - "80:80"
      - "443:443"
      - "5000:5000"
  server:
    container_name: server
    image: elfensky/mssl-server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"




  
  
  
  
  
