version: '3'
services:

  proxy:
    container_name: proxy
    image: nginx:latest
    volumes:  
      - ./nginx/logs:/logs:rw
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    server:
    container_name: server
    image: elfensky/mssl-server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    # ports:
    #   - "4000:4000"
    expose:
      - "4000"




  
  
  
  
  
